/**
 * FILE PURPOSE: Type definitions for all detectors
 *
 * CONTEXT: Shared types used across all detector implementations.
 * Provides consistent interface for detection results, issues, and detector contracts.
 *
 * DEPENDENCIES: None (base types)
 *
 * AUTHOR: Claude Code
 * LAST UPDATED: 2025-11-06
 */

/**
 * Severity levels for detected issues
 *
 * WHY: Prioritize issues for developers (critical = breaks build, low = suggestion)
 *
 * - critical: Breaks build or causes runtime errors (fake packages, syntax errors)
 * - high: Major issues that should be fixed before commit (deprecated APIs, security)
 * - medium: Code quality issues (type safety, complexity)
 * - low: Suggestions and best practices (formatting, naming)
 */
export type Severity = 'critical' | 'high' | 'medium' | 'low';

/**
 * Detected issue with location and suggested fix
 *
 * WHY: Provide developers with actionable information to fix issues
 * HOW: Include file location, description, and optional fix suggestion
 *
 * EXAMPLE:
 * ```typescript
 * {
 *   id: 'fake-package-stripe-pro',
 *   severity: 'critical',
 *   category: 'hallucination',
 *   filePath: 'src/payment.ts',
 *   line: 5,
 *   column: 25,
 *   message: "Package 'stripe-pro' does not exist",
 *   suggestion: "Use 'stripe' instead",
 *   evidence: "import { Stripe } from 'stripe-pro';",
 *   fix: {
 *     type: 'string-replace',
 *     search: "'stripe-pro'",
 *     replace: "'stripe'"
 *   }
 * }
 * ```
 */
export interface Issue {
  /** Unique identifier for this issue type (e.g., 'fake-package', 'deprecated-api') */
  id: string;

  /** Severity level (critical, high, medium, low) */
  severity: Severity;

  /** Category of issue (hallucination, code-quality, security, performance, requirements, architecture) */
  category: 'hallucination' | 'code-quality' | 'security' | 'performance' | 'requirements' | 'architecture';

  /** File path where issue was detected */
  filePath: string;

  /** Line number (1-indexed) */
  line: number;

  /** Column number (1-indexed, optional) */
  column?: number;

  /** Human-readable description of the issue */
  message: string;

  /** Suggested fix or action to take */
  suggestion?: string;

  /** Code snippet showing the issue */
  evidence: string;

  /** Automated fix proposal (if available) */
  fix?: Fix;

  /** Additional metadata (package name, API method, etc.) */
  metadata?: Record<string, unknown>;
}

/**
 * Automated fix proposal
 *
 * WHY: Enable LLM-powered auto-fix with Proposer→Solver→Judge pipeline
 * HOW: Describe fix as string replacement (MVP) or AST transformation (future)
 *
 * TYPES:
 * - string-replace: Simple find/replace (MVP implementation)
 * - regex-replace: Pattern-based replacement
 * - ast-transform: Structural code changes (Phase 2)
 * - llm-generated: Fix generated by LLM (requires validation)
 */
export interface Fix {
  /** Type of fix to apply */
  type: 'string-replace' | 'regex-replace' | 'ast-transform' | 'llm-generated';

  /** Search pattern (string or regex) */
  search: string | RegExp;

  /** Replacement text */
  replace: string;

  /** Confidence score (0.0-1.0) for LLM-generated fixes */
  confidence?: number;

  /** Explanation of what the fix does */
  explanation?: string;
}

/**
 * Result from running a detector
 *
 * WHY: Standardize detector output for aggregation and reporting
 * HOW: Include all detected issues plus execution metadata
 *
 * EXAMPLE:
 * ```typescript
 * {
 *   detectorName: 'hallucination',
 *   success: true,
 *   issues: [
 *     { id: 'fake-package', severity: 'critical', ... },
 *     { id: 'deprecated-api', severity: 'high', ... }
 *   ],
 *   metadata: {
 *     filesAnalyzed: 5,
 *     executionTimeMs: 120,
 *     packagesChecked: 12,
 *     npmRegistryHits: 12
 *   }
 * }
 * ```
 */
export interface DetectorResult {
  /** Name of the detector that produced this result */
  detectorName: string;

  /** Whether the detector executed successfully */
  success: boolean;

  /** All issues detected (empty array if none) */
  issues: Issue[];

  /** Error message if detector failed */
  error?: string;

  /** Execution metadata (timing, stats, etc.) */
  metadata: {
    /** Number of files analyzed */
    filesAnalyzed: number;

    /** Execution time in milliseconds */
    executionTimeMs: number;

    /** Detector-specific stats */
    [key: string]: unknown;
  };
}

/**
 * File to be analyzed by detectors
 *
 * WHY: Pass file content and metadata to detectors
 * HOW: Include path, content, and git status
 */
export interface AnalysisFile {
  /** Absolute path to file */
  path: string;

  /** File content as string */
  content: string;

  /** Git status (staged, modified, etc.) */
  gitStatus?: 'staged' | 'modified' | 'untracked';

  /** File extension for quick filtering (optional) */
  extension?: string;
}

/**
 * Detector interface - all detectors must implement this
 *
 * WHY: Consistent API for running detectors, enables plugin architecture
 * HOW: Each detector implements detect() method and declares file types it handles
 *
 * EXAMPLE:
 * ```typescript
 * export class HallucinationDetector implements IDetector {
 *   readonly name = 'hallucination';
 *   readonly supportedExtensions = ['.ts', '.js', '.tsx', '.jsx'];
 *
 *   async detect(files: AnalysisFile[]): Promise<DetectorResult> {
 *     // Detection logic
 *   }
 * }
 * ```
 */
export interface IDetector {
  /** Unique detector name (hallucination, code-quality, etc.) */
  readonly name: string;

  /** File extensions this detector can analyze */
  readonly supportedExtensions: string[];

  /**
   * Run detection on provided files
   *
   * @param files - Files to analyze
   * @returns Detection result with all issues found
   */
  detect(files: AnalysisFile[]): Promise<DetectorResult>;
}

/**
 * Configuration for detectors
 *
 * WHY: Allow users to customize detector behavior via .llm-guardian.json
 */
export interface DetectorConfig {
  /** Enable/disable this detector */
  enabled: boolean;

  /** Detector-specific settings */
  [key: string]: unknown;
}
