/**
 * FILE PURPOSE: Init command - Install git pre-commit hook
 *
 * CONTEXT: Sets up LLM Guardian as a git pre-commit hook.
 * Default is non-blocking (warns but allows commit).
 *
 * DEPENDENCIES:
 * - fs: File operations
 * - git: Hook installation
 *
 * AUTHOR: Claude Code
 * LAST UPDATED: 2025-11-06
 */

import chalk from 'chalk';
import { existsSync, writeFileSync, chmodSync } from 'fs';
import { join } from 'path';
import inquirer from 'inquirer';
import { isGitRepository, getGitRoot } from '../utils/git.js';

/**
 * Init command options
 */
interface InitOptions {
  force?: boolean;
  blocking?: boolean;
}

/**
 * Run init command
 *
 * WHY: Install pre-commit hook for automatic code checking
 * HOW: Create .git/hooks/pre-commit script
 *
 * @param options - Command-line options
 *
 * HOOK BEHAVIOR:
 * - Non-blocking (default): Warns on issues, allows commit
 * - Blocking (--blocking): Prevents commit on critical/high issues
 *
 * EXIT CODES:
 * - 0: Success (hook installed)
 * - 1: Error (not git repo, hook exists without --force)
 */
export async function initCommand(options: InitOptions): Promise<void> {
  try {
    // Verify git repository
    if (!isGitRepository()) {
      console.error(chalk.red('❌ Not a git repository'));
      console.error(chalk.dim('Initialize git first: git init'));
      process.exit(1);
    }

    const gitRoot = getGitRoot();
    const hookPath = join(gitRoot, '.git', 'hooks', 'pre-commit');

    // Check if hook already exists
    if (existsSync(hookPath) && !options.force) {
      console.error(chalk.red('❌ Pre-commit hook already exists'));
      console.error(chalk.dim(`Path: ${hookPath}`));
      console.error(chalk.dim('Use --force to overwrite'));
      process.exit(1);
    }

    // Confirm installation
    console.log(chalk.bold('🛡️  LLM Guardian - Git Hook Installation'));
    console.log(chalk.dim('━'.repeat(50)));
    console.log(`${chalk.dim('Hook location:')} ${hookPath}`);
    console.log(`${chalk.dim('Mode:')} ${options.blocking ? chalk.yellow('Blocking') : chalk.green('Non-blocking')}`);
    console.log('');

    const { confirm } = await inquirer.prompt([
      {
        type: 'confirm',
        name: 'confirm',
        message: 'Install pre-commit hook?',
        default: true,
      },
    ]);

    if (!confirm) {
      console.log(chalk.dim('Installation cancelled'));
      process.exit(0);
    }

    // Generate hook script
    const hookScript = generateHookScript(options.blocking || false);

    // Write hook file
    writeFileSync(hookPath, hookScript, 'utf-8');

    // Make hook executable
    chmodSync(hookPath, '755');

    // Success message
    console.log(chalk.green('\n✅ Pre-commit hook installed successfully!\n'));
    console.log(chalk.dim('The hook will run automatically on `git commit`'));
    console.log(chalk.dim('To run manually: llm-guardian check\n'));

  } catch (error) {
    console.error(chalk.red('\n❌ Failed to install hook:'));
    console.error(chalk.red(error instanceof Error ? error.message : String(error)));
    process.exit(1);
  }
}

/**
 * Generate pre-commit hook script
 *
 * WHY: Create hook that runs LLM Guardian on commit
 * HOW: Shell script that calls llm-guardian check
 *
 * @param blocking - Whether hook should block commits
 * @returns Hook script content
 *
 * SCRIPT BEHAVIOR:
 * - Runs `llm-guardian check` on staged files
 * - Non-blocking: Warns but exit 0 (allows commit)
 * - Blocking: Exit with llm-guardian's exit code (blocks on issues)
 */
function generateHookScript(blocking: boolean): string {
  return `#!/bin/sh
# LLM Guardian Pre-Commit Hook
# Auto-generated by: llm-guardian init
# Mode: ${blocking ? 'BLOCKING' : 'NON-BLOCKING'}

# Run LLM Guardian on staged files
npx llm-guardian check

# Capture exit code
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
  echo ""
  echo "⚠️  LLM Guardian found issues in staged files"

${blocking
  ? `  echo "❌ Commit blocked (use --no-verify to skip)"
  exit $EXIT_CODE`
  : `  echo "⚠️  Committing anyway (non-blocking mode)"
  echo "💡 Fix issues or use --blocking mode: llm-guardian init --blocking --force"
  exit 0`
}
fi

exit 0
`;
}
